<a href="https://colab.research.google.com/github/srujanachoudary/NumPy/blob/main/AIDS_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [3]:
import numpy as np
arr_0d=np.array(4)
print(arr_0d)
arr_1d=np.array([1,2,3])
print(arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)

4
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
arr_0d=np.array(4)
arr_1d=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

0
1
2
3


In [10]:
zeros=np.zeros((2,3))
print(zeros)
ones=np.ones((3,3))
print(ones)
random_arr=np.random.random((2,2))
print(random_arr)
#indentity matrix
identity_matrix=np.eye(3)
print(identity_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.72131357 0.76645697]
 [0.96909825 0.74815097]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
range_ar=np.arange(0,12,3) #start,stop,step
print(range_ar)

[0 3 6 9]


In [14]:
#Array attributes
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(2, 3)
6
int64
2


In [27]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data.shape)
print(temp_data.size)
print(temp_data.dtype)
print(temp_data.ndim)
gh3=np.array([21,23,22])
updated_temp_data=np.vstack([temp_data,gh3])
print(updated_temp_data)
print()
sensor_array_flags=np.zeros((2,3))
print(sensor_array_flags)
print()
greenhouse_identity=np.eye(3)
print(greenhouse_identity)

(2, 3)
6
int64
2
[[22 25 20]
 [24 26 23]
 [21 23 22]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
#indexing and slicing
arr=np.array([[34,24,35],[12,89,67]])
print(arr[1,2])
print(arr[1,-1])
print(arr[:,1:])
print(arr[0:2,1:3])

67
67
[[24 35]
 [89 67]]
[[24 35]
 [89 67]]


Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [41]:
shipments=np.array([[50,40],[60,45],[55,50],[70,60],[65,55],[80,70],[90,75]])
print(shipments)
print("Apples shipped on wednesday",shipments[2,0])
print("Oranges shipped on sunday",shipments[6,1])
print("weekday shipments ",shipments[0:5,0:2])
print("weekend shipments",shipments[5:7,0:2])
print("apples shipments from wednesday to saturday",shipments[2:6,0])
shipments[5,0]=100
print(shipments)

[[50 40]
 [60 45]
 [55 50]
 [70 60]
 [65 55]
 [80 70]
 [90 75]]
Apples shipped on wednesday 55
Oranges shipped on sunday 75
weekday shipments  [[50 40]
 [60 45]
 [55 50]
 [70 60]
 [65 55]]
weekend shipments [[80 70]
 [90 75]]
apples shipments from wednesday to saturday [55 70 65 80]
[[ 50  40]
 [ 60  45]
 [ 55  50]
 [ 70  60]
 [ 65  55]
 [100  70]
 [ 90  75]]


In [44]:
#arrray operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a*2)

[5 7 9]
[ 4 10 18]
[2 4 6]


In [45]:
#matrix operations
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
#multiplication
res=np.dot(m1,m2)
print(res)

[[19 22]
 [43 50]]


In [47]:
#Broadcasting
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3])
print(a+b)
c=3
print(a+c)
print(b+c)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[4 5 6]


In [51]:
import numpy as np

# 🔹 Universal functions
arr = np.array([5, 6, 7])
print("√ Square Root:", np.sqrt(arr))
print("e^ Exponential:", np.exp(arr))

# 🔹 1. Arithmetic functions (element-wise)
x = np.array([3, 2, 1])
y = np.array([6, 7, 8])

print("\n--- Arithmetic Functions ---")
print("Add:", np.add(x, y))
print("Subtract:", np.subtract(x, y))
print("Multiply:", np.multiply(x, y))
print("Divide:", np.divide(x, y))
print("Power:", np.power(x, y))
print("Modulo:", np.mod(x, y))

# 🔹 2. Exponential and Logarithmic ufuncs
print("\n--- Exponential & Logarithmic Functions ---")
print("exp(x):", np.exp(x))
print("log(x):", np.log(x))
print("log10(x):", np.log10(x))
print("log2(x):", np.log2(x))
print("expm1(x):", np.expm1(x))  # exp(x) - 1 (more precise for small x)

# 🔹 3. Trigonometric ufuncs
print("\n--- Trigonometric Functions ---")
print("sin(x):", np.sin(x))
print("cos(x):", np.cos(x))
print("tan(x):", np.tan(x))
print("arcsin(x/10):", np.arcsin(x / 10))  # scaled so values are valid (-1 to 1)
print("arccos(x/10):", np.arccos(x / 10))
print("arctan(x):", np.arctan(x))
print("degrees(x):", np.degrees(x))
print("radians(x):", np.radians(x))

# 🔹 4. Rounding ufuncs
print("\n--- Rounding Functions ---")
print("Round:", np.round(x))
print("Floor:", np.floor(x))
print("Ceil:", np.ceil(x))
print("Trunc:", np.trunc(x))

# 🔹 5. Statistical ufuncs
print("\n--- Statistical Functions ---")
print("Min:", np.min(x))
print("Max:", np.max(x))
print("Mean:", np.mean(x))
print("Std:", np.std(x))
print("Var:", np.var(x))
print("Sum:", np.sum(x))
print("Product:", np.prod(x))

# 🔹 6. Logical ufuncs
print("\n--- Logical Functions ---")
print("Logical AND:", np.logical_and(x > 1, y > 6))
print("Logical OR:", np.logical_or(x > 1, y > 6))
print("Logical NOT:", np.logical_not(x > 1))
print("Logical XOR:", np.logical_xor(x > 1, y > 6))

# 🔹 7. Comparison ufuncs
print("\n--- Comparison Functions ---")
print("Greater:", np.greater(x, y))
print("Less:", np.less(x, y))
print("Equal:", np.equal(x, y))
print("Not Equal:", np.not_equal(x, y))
print("Greater Equal:", np.greater_equal(x, y))
print("Less Equal:", np.less_equal(x, y))

# 🔹 8. Bitwise ufuncs (on integers)
print("\n--- Bitwise Functions ---")
print("Bitwise AND:", np.bitwise_and(x, y))
print("Bitwise OR:", np.bitwise_or(x, y))
print("Bitwise XOR:", np.bitwise_xor(x, y))
print("Bitwise NOT:", np.invert(x))


√ Square Root: [2.23606798 2.44948974 2.64575131]
e^ Exponential: [ 148.4131591   403.42879349 1096.63315843]

--- Arithmetic Functions ---
Add: [9 9 9]
Subtract: [-3 -5 -7]
Multiply: [18 14  8]
Divide: [0.5        0.28571429 0.125     ]
Power: [729 128   1]
Modulo: [3 2 1]

--- Exponential & Logarithmic Functions ---
exp(x): [20.08553692  7.3890561   2.71828183]
log(x): [1.09861229 0.69314718 0.        ]
log10(x): [0.47712125 0.30103    0.        ]
log2(x): [1.5849625 1.        0.       ]
expm1(x): [19.08553692  6.3890561   1.71828183]

--- Trigonometric Functions ---
sin(x): [0.14112001 0.90929743 0.84147098]
cos(x): [-0.9899925  -0.41614684  0.54030231]
tan(x): [-0.14254654 -2.18503986  1.55740772]
arcsin(x/10): [0.30469265 0.20135792 0.10016742]
arccos(x/10): [1.26610367 1.36943841 1.47062891]
arctan(x): [1.24904577 1.10714872 0.78539816]
degrees(x): [171.88733854 114.59155903  57.29577951]
radians(x): [0.05235988 0.03490659 0.01745329]

--- Rounding Functions ---
Round: [3 2 1]
Fl

In [52]:
#Aggregation functions
arr=np.array([1,2,3,4])
print("sum",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard deviation:",np.std(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

sum 10
Mean: 2.5
Standard deviation: 1.118033988749895
Max: 4
Min: 1


In [75]:
farma=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmb=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmc=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
stackfarm=np.stack((farma,farmb,farmc))
print(stackfarm)
print(np.shape(stackfarm))
print(np.size(stackfarm))
print(stackfarm.dtype)
print(np.ndim(stackfarm))
energy_per_farm=np.sum(stackfarm,axis=(1,2))
print("total energy per farm:",energy_per_farm)
print("Mean :",np.mean(stackfarm,axis=(1,2)))
print("std :",np.std(stackfarm,axis=(1,2)))
print("variance :",np.var(stackfarm,axis=(1,2)))
hour_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.dot(stackfarm,hour_weights)
print("weighted per panel",weighted_per_panel)


[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
(3, 4, 3)
36
int64
3
total energy per farm: [126 234 174]
Mean : [10.5 19.5 14.5]
std : [1.97905701 1.97905701 1.97905701]
variance : [3.91666667 3.91666667 3.91666667]
weighted per panel [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]


In [77]:
stackfarm = stackfarm.astype(float)
stackfarm[1]+=0.5
print("Updated farm B",stackfarm[1])


Updated farm B [[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]]


In [80]:
# Per-farm mean & std along panels & hours (axis=(1,2)), keepdims for broadcasting
mean_per_farm = np.mean(stackfarm, axis=(1,2), keepdims=True)
std_per_farm = np.std(stackfarm, axis=(1,2), keepdims=True)

# Z-score normalize
normalized = (stackfarm - mean_per_farm) / std_per_farm
print("Normalized shape:", normalized.shape)
print("Normalized data:")
print(normalized)

Normalized shape: (3, 4, 3)
Normalized data:
[[[-0.25264558  0.75793673  0.25264558]
  [-0.75793673  0.25264558 -0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]

 [[ 0.25264558 -0.25264558  0.75793673]
  [-0.75793673  0.25264558 -0.25264558]
  [ 1.26322788  1.76851903  0.75793673]
  [-1.26322788 -0.75793673 -1.76851903]]

 [[ 0.25264558  0.75793673 -0.25264558]
  [-0.25264558 -0.75793673  0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]]


In [86]:
#exponential family
exp_norm = np.exp(normalized)
expm1_norm = np.expm1(normalized)
log_norm = np.log(normalized - np.min(normalized) + 1e-6)   # shift to positive
log10_norm = np.log10(normalized - np.min(normalized) + 1e-6)
log2_norm = np.log2(normalized - np.min(normalized) + 1e-6)


#trigonometry
sin_norm = np.sin(normalized)
cos_norm = np.cos(normalized)
tan_norm = np.tan(normalized)
arctan_norm = np.arctan(normalized)
# arcsin/arccos require inputs in [-1,1]
scaled_norm = np.clip(normalized, -1, 1)
arcsin_norm = np.arcsin(scaled_norm)
arccos_norm = np.arccos(scaled_norm)
degrees_norm = np.degrees(normalized)
radians_norm = np.radians(normalized)
#rounding functions
round_norm = np.round(normalized)
floor_norm = np.floor(normalized)
ceil_norm = np.ceil(normalized)
trunc_norm = np.trunc(normalized)
#logical and comparison functions
# Example: high output mask (>20 kWh)
high_output = stackfarm > 20
even_hours_mask = (np.arange(stackfarm.shape[2]) % 2 == 0)  # shape (3,)
# Broadcast over hours
even_hours_mask = even_hours_mask.reshape(1,1,-1)

logical_and_mask = np.logical_and(high_output, even_hours_mask)
logical_or_mask = np.logical_or(high_output, even_hours_mask)
logical_not_mask = np.logical_not(high_output)
logical_xor_mask = np.logical_xor(high_output, even_hours_mask)

greater_eq_mask = np.greater_equal(stackfarm, 15)
less_mask = np.less(stackfarm, 12)

alerts = np.array([
    [[1,0,1],
     [0,0,1],
     [1,1,0],
     [0,1,0]],

    [[0,1,1],
     [1,0,0],
     [1,1,1],
     [0,0,1]],

    [[1,1,0],
     [0,1,1],
     [1,0,1],
     [1,0,0]]
], dtype=int)

bitwise_and_alerts = np.bitwise_and(alerts, 1)
bitwise_or_alerts = np.bitwise_or(alerts, 0)
bitwise_invert_alerts = np.bitwise_not(alerts)

add_norm = np.add(normalized, 1)
sub_norm = np.subtract(normalized, 1)
mul_norm = np.multiply(normalized, 2)
div_norm = np.divide(normalized, 2)
power_norm = np.power(normalized, 2)
mod_norm = np.mod(np.floor(normalized*10).astype(int), 3)

# Total per panel (sum across hours)
panel_totals_per_farm = np.sum(stackfarm, axis=2)  # shape (3,4)

# Boolean: True if any panel < 40
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("Panel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance per farm:", needs_maintenance)

overall_total = np.sum(stackfarm)
peak_hour_value = np.max(stackfarm)
peak_index_flat = np.argmax(stackfarm)
peak_farm, peak_panel, peak_hour = np.unravel_index(peak_index_flat, stackfarm.shape)

average_per_panel = np.mean(stackfarm, axis=2)  # shape (3,4)

print("\nOverall total energy:", overall_total)
print("Peak hour value:", peak_hour_value, "at Farm", peak_farm, "Panel", peak_panel, "Hour", peak_hour)
print("Average energy per panel across hours:\n", average_per_panel)


[[[0.77674313 2.13386893 1.2874269 ]
  [0.46863235 1.2874269  0.77674313]
  [2.13386893 3.53681952 5.86216526]
  [0.2827399  0.17058543 0.46863235]]

 [[1.2874269  0.77674313 2.13386893]
  [0.46863235 1.2874269  0.77674313]
  [3.53681952 5.86216526 2.13386893]
  [0.2827399  0.46863235 0.17058543]]

 [[1.2874269  2.13386893 0.77674313]
  [0.77674313 0.46863235 1.2874269 ]
  [2.13386893 3.53681952 5.86216526]
  [0.2827399  0.17058543 0.46863235]]]
Panel totals per farm:
 [[33.  30.  39.  24. ]
 [61.5 58.5 67.5 52.5]
 [45.  42.  51.  36. ]]
Needs maintenance per farm: [ True False  True]

Overall total energy: 540.0
Peak hour value: 23.5 at Farm 1 Panel 2 Hour 1
Average energy per panel across hours:
 [[11.  10.  13.   8. ]
 [20.5 19.5 22.5 17.5]
 [15.  14.  17.  12. ]]


In [90]:
#reshaping arrays
arr=np.array([1,2,3,4,5,6,7,8])
reshaped=arr.reshape(4,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [99]:
#stacking and splitting
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
#vertical stack
vstacked=np.vstack((arr1,arr2))
print(vstacked)
#horizontal stack
hstacked=np.hstack((arr1,arr2))
print(hstacked)
#splitting
print(np.array_split(hstacked,5))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [104]:
#advanced indexing
#a.boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
#b.fancy indexing
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])

[4 5]
[10 30]


copy vs view

In [109]:
import numpy as np
arr=np.array([1,2,3,4,5])
#view shares memory
view=arr.view()
view[0]=10
print(arr)

#copy does not share memory
copy=arr.copy()
copy[2]=36
print(arr)
print(copy)

[10  2  3  4  5]
[10  2  3  4  5]
[10  2 36  4  5]


Saving and loading

In [110]:
#a.save to a ile
arr=np.array([1,2,3,4,5])
np.save('array.npy',arr)
#b.load from a file
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3 4 5]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [140]:
arr_1d=np.arange(10,51)
random_arr=np.random.rand(3,3)
print(np.shape(arr_1d))
print(np.size(arr_1d))
print(arr_1d.dtype)
print(np.shape(random_arr))
print(np.size(random_arr))
print(random_arr.dtype)
arr_plus5=arr_1d+5
print(arr_plus5)
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
elementwise_product = A * B
print("element wise product: ",elementwise_product)
arr_5x5=np.arange(1,26).reshape(5,5)
print(arr_5x5)
print("first row",arr_5x5[0,:])
print("first column",arr_5x5[:,0])
print("Last column",arr_5x5[:,-1])
print("first 3 rows and first 2 columns:",arr_5x5[:3,:2])
rand_ints=np.random.randint(10,101,10)
print(rand_ints)
print("minimium:",np.max(rand_ints))
print("maximum:",np.min(rand_ints))
print("mean:",np.mean(rand_ints))
print("standard deviation:",np.std(rand_ints))
reshaping=np.arange(1,13).reshape(3,4)
print(reshaping)
matrix_ones=np.ones((3,3))
row_array=np.array([1,2,3])
broadcasting=matrix_ones+row_array
print(broadcasting)
rand=np.random.randint(1,50,10)
divisibleby5=rand[rand%5==0]
print("divisible by 5 are:",divisibleby5)
M1 = np.array([[1,2],[3,4]])
M2 = np.array([[5,6],[7,8]])
matrix_product = np.dot(M1, M2)
print("\nMatrix multiplication result:\n", matrix_product)
arr_4x4 = np.arange(1,17).reshape(4,4)
print("diagonal elements are ",arr_4x4[np.arange(4),np.arange(4)])

(41,)
41
int64
(3, 3)
9
float64
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
element wise product:  [[ 5 12]
 [21 32]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row [1 2 3 4 5]
first column [ 1  6 11 16 21]
Last column [ 5 10 15 20 25]
first 3 rows and first 2 columns: [[ 1  2]
 [ 6  7]
 [11 12]]
[86 87 48 82 87 36 81 37 39 89]
minimium: 89
maximum: 36
mean: 67.2
standard deviation: 22.520213142863458
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
divisible by 5 are: [25 20 25]

Matrix multiplication result:
 [[19 22]
 [43 50]]
diagonal elements are  [ 1  6 11 16]
